name: e2e_race
on: pull_request
jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.17

    - name: Check out code
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go mod download

    - name: Run make minimaltools
      run: |
        make minimaltools

    - name: e2e_race
      run: |
        make e2e_test_race
